name: insurance_claim_app
description: Insurance Claim Management System for Medoc Flutter Intern Assignment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  uuid: ^4.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/medoc_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/medoc_icon.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  branding_mode: center
