name: insurance_claim_app
description: Insurance Claim Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2  # State management
  fl_chart: ^0.68.0  # Dashboard charts
  intl: ^0.19.0     # Date/currency formatting
  uuid: ^4.5.0      # Unique IDs for claims/bills
  hive: ^2.2.3          # Core Hive
  hive_flutter: ^1.1.0  # Flutter integration 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/medoc_icon.png"
  min_sdk_android: 21   # optional, default is fine
  remove_alpha_ios: true  # removes transparency if needed for iOS

flutter_native_splash:
  color: "#FFFFFF"                  # background color
  image: assets/icon/medoc_icon.png 
  android: true
  ios: true
  web: false                        # web splash is different
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  branding_mode: center             # optional
